# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.15.1"
minimal_mistakes_skin: "haxor" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "Spain"
title: "404zzero.github.io"
title_separator: "-"
name: "404_zzero"
description: "cybersecurity and ethical hacking"
url: "https://404-zzero.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g., "/blog"
repository: "slemire/slemire.github.io"
logo: "/assets/images/masthead.png"
teaser: # Optional, path to fallback teaser image
breadcrumbs: true
words_per_minute: 200

# Comments
comments:
  provider: false # Options: false, "disqus", "discourse", etc.

# Social Sharing
twitter:
  username: ""
facebook:
  username: ""
  app_id: ""
  publisher: ""
og_image: # Optional Open Graph/Twitter default site image

# Social Profiles
social:
  type: Person
  name: "404_zzero"
  links: [] # Add URLs to social profiles here, e.g., ["https://twitter.com/yourprofile"]

# Analytics
analytics:
  provider: "google"
  Google:
    tracking_id: "UA-145129883-1"
    anonymize_ip: false

# Author Information
author:
  name: "404_zzero"
  avatar: "/assets/images/avatar.png"
  bio: "aspiring pentester and Red team, programmer and linux enthusiast"
  location: "Spain"
  email: "plgggg358@gmail.com"
  github: "404zzero"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn

# Encoding and Markdown
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Kramdown Settings
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:title/
paginate: 10
paginate_path: /page:num/
timezone: "" # Add timezone if needed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
